#ifndef __PARTDEFINE_H_INCLUDED__
#define __PARTDEFINE_H_INCLUDED__

typedef enum {
	PART_BACK_SONG_SELECT,
	PART_START,
	PART_COUNTDOWN,
	PART_PLAY,
	PART_PAUSE,
	PART_REWIND,
	PART_SETTING,
	PART_NEXT
} PartScene;

#endif