#ifndef __PARTRESULTDEFINE_H_INCLUDED__
#define __PARTRESULTDEFINE_H_INCLUDED__

typedef enum {
	PART_RESULT_BACK_SONG_SELECT,
	PART_RESULT_BACK_PLAY,
	PART_RESULT_TOP,
	PART_RESULT_FINISH,
	PART_RESULT_BACK_THROUGH_OPTION,
	PART_RESULT_BACK_PART_OPTION
} PartResultScene;

#endif