#ifndef __THROUGHRESULTDEFINE_H_INCLUDED__
#define __THROUGHRESULTDEFINE_H_INCLUDED__

typedef enum {
	THROUGH_BACK_TOP,
	THROUGH_RESULT_BACK_SONG_SELECT,
	THROUGH_RESULT_TOP,
	THROUGH_RESULT_DETAIL,
	THROUGH_RESULT_FINISH
} ThroughResultScene;

#endif