#ifndef __THROUGHDEFINE_H_INCLUDED__
#define __THROUGHDEFINE_H_INCLUDED__

typedef enum {
	THROUGH_BACK_TOP,
	THROUGH_BACK_SONG_SELECT,
	THROUGH_START,
	THROUGH_COUNTDOWN,
	THROUGH_PLAY,
	THROUGH_PAUSE,
	THROUGH_RESULT,
	THROUGH_SETTING,
	THROUGH_DETAIL,
	THROUGH_FINISH
} ThroughScene;

#endif