#ifndef __THROUGHDEFINE_H_INCLUDED__
#define __THROUGHDEFINE_H_INCLUDED__

#define THROUGH_START 0
#define THROUGH_PLAY 1
#define THROUGH_PAUSE 2
#define THROUGH_RESULT 3
#define THROUGH_SETTING 4
#define THROUGH_DETAIL 5

#endif