#ifndef __THROUGHDEFINE_H_INCLUDED__
#define __THROUGHDEFINE_H_INCLUDED__

#define BACK_SONG_SELECT -1
#define THROUGH_START 0
#define THROUGH_COUNTDOWN 1
#define THROUGH_PLAY 2
#define THROUGH_PAUSE 3
#define THROUGH_RESULT 4
#define THROUGH_SETTING 5
#define THROUGH_DETAIL 6
#define THROUGH_FINISH 7

#endif